### PR TITLE
Add org link, contributions for the day and minor fixes

### LINKED ISSUE #1: GitHub card
Generate a embedded GitHub card for username.

~Fields : **Thumbnail, repos, stars, forks, bio, followers/following, contri streak**~
**Make org links clickable**

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #1 #3

PS: The contribution data will get fetched for the new day around 1:30, due to Timezone issues.

*After:*

image

### CODE REVIEW

**Comment by anshumanv** [comment]
This is quality work, needs merging. ✅

**Review by mohitkyadav — COMMENTED** [review]
@aashutoshrathi can you make the indentation to 2 spaces, it's also there in the .editorconfig

**Comment by aashutoshrathi** [comment]
Oh it was 2 spaces, doing it.

**Comment by aashutoshrathi** [comment]
@mohitkyadav liar. Check your editorconfig.
I think we should handle this stuff in another PR

**Comment by aashutoshrathi** [comment]
Also, I request you to install [this](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and open and save all files once by yourself.

**Comment by mohitkyadav** [comment]
so sorry, 😆  ok

**Comment by anshumanv** [comment]
Thank you Nimbahera Aashutosh and Kherli Mukul.

**Pull request merged**
