### PR TITLE
indent

### PR DESCRIPTION
**Pull request by mohitkyadav**

### CODE REVIEW

**Comment by mohitkyadav** [comment]
@aashutoshrathi

**Review by aashutoshrathi — APPROVED** [review]
LGTM if you used https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
Also, make sure you opened all files.

**Comment by aashutoshrathi** [comment]
Fixes #8

**Comment by aashutoshrathi** [comment]
Feel free to merge @mohitkyadav

**Comment by aashutoshrathi** [comment]
There is a green button saying 'Merge'. 😄

**Pull request merged**
